# SwiftLint Configuration for W8Trackr
# A SwiftUI + SwiftData iOS weight tracking app

# ============================================================================
# INCLUDED/EXCLUDED PATHS
# ============================================================================
included:
  - W8Trackr
  - W8TrackrTests
  - W8TrackrUITests

excluded:
  - .build
  - DerivedData
  - Pods
  - Carthage

# ============================================================================
# DISABLED RULES
# ============================================================================
# Rules that conflict with SwiftUI patterns or project conventions
disabled_rules:
  # SwiftUI views often have longer bodies with nested modifiers
  - function_body_length

  # Force unwrapping is occasionally needed and used intentionally
  - force_unwrapping

  # Force try is sometimes appropriate in controlled contexts
  - force_try

  # Large tuples are used in SwiftUI Charts and data processing
  - large_tuple

  # Trailing closure is preferred in SwiftUI, warning not needed
  - trailing_closure

  # Multiple closures with trailing closure is common in SwiftUI
  - multiple_closures_with_trailing_closure

  # Nesting is common with SwiftUI view composition
  - nesting

# ============================================================================
# OPT-IN RULES
# ============================================================================
opt_in_rules:
  # Readability
  - empty_count
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - last_where

  # Modernization
  - prefer_zero_over_explicit_init

  # Safety
  - empty_string
  - fallthrough
  - override_in_extension

  # SwiftUI-friendly
  - toggle_bool

# ============================================================================
# RULE CONFIGURATION
# ============================================================================

# Line length: SwiftUI modifier chains can get long
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

# Type body length: SwiftUI views can be larger
type_body_length:
  warning: 400
  error: 600

# File length: Reasonable but not too strict
# Test files can legitimately be longer
file_length:
  warning: 700
  error: 1000
  ignore_comment_only_lines: true

# Identifier names: Allow short names common in Swift
identifier_name:
  min_length:
    warning: 1  # Allow single char like 'i', 'x', 'a'
  max_length:
    warning: 50
    error: 60
  allowed_symbols:
    - _
  excluded:
    - id
    - to
    - lb
    - kg

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Colon spacing
colon:
  apply_to_dictionaries: true

# Type name length
type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID

# ============================================================================
# CUSTOM RULES
# ============================================================================
custom_rules:
  # Discourage print statements in production code
  no_print_statements:
    regex: "\\bprint\\s*\\("
    message: "Consider using os_log or removing print statements"
    severity: warning

  # Encourage TODO/FIXME to have associated issue tracking
  todo_without_reference:
    regex: "//\\s*(TODO|FIXME)(?!:.*#)"
    message: "Consider adding an issue reference to TODO/FIXME comments"
    severity: warning
